import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/common/NavBar";
import { GoogleOAuthProvider } from "@react-oauth/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: React.PropsWithChildren) {
  return (
    <html lang="en">
      <body className="antialiased">
        <GoogleOAuthProvider clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID as string}>
          <NavBar />
          {children}
        </GoogleOAuthProvider>;
      </body>
    </html>
  );
}
